import nextVitals from 'eslint-config-next/core-web-vitals';
import nextTs from 'eslint-config-next/typescript';
import prettierConfig from 'eslint-config-prettier';
import prettierPlugin from 'eslint-plugin-prettier';
import reactRefresh from 'eslint-plugin-react-refresh';
import { defineConfig, globalIgnores } from 'eslint/config';

// eslint-disable-next-line import/no-default-export
export default defineConfig([
  globalIgnores(['.next/**', 'out/**', 'build/**', 'next-env.d.ts']),

  ...nextVitals,
  ...nextTs,

  // Prettier integration (must be last)
  prettierConfig,
  {
    plugins: {
      prettier: prettierPlugin,
      'react-refresh': reactRefresh,
    },
    rules: {
      'prettier/prettier': 'warn',

      '@typescript-eslint/ban-ts-comment': 'warn',
      '@typescript-eslint/default-param-last': 'warn',
      '@typescript-eslint/no-empty-interface': 'warn',
      '@typescript-eslint/no-empty-object-type': 'warn',
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-shadow': 'warn',
      '@typescript-eslint/no-use-before-define': 'warn',
      '@typescript-eslint/no-unnecessary-type-constraint': 'warn',
      '@typescript-eslint/no-unsafe-function-type': 'warn',
      '@typescript-eslint/no-unused-expressions': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          vars: 'all',
          args: 'after-used',
          ignoreRestSiblings: true,
        },
      ],
      '@typescript-eslint/prefer-as-const': 'warn',

      'array-callback-return': 'warn',
      'arrow-body-style': 'warn',
      camelcase: 'warn',
      'class-methods-use-this': 'warn',
      'consistent-return': 'warn',
      'default-case': 'warn',
      'default-case-last': 'warn',
      'default-param-last': 'warn',
      'dot-notation': 'off', // Handled by @typescript-eslint/dot-notation
      eqeqeq: 'warn',
      'func-style': ['warn', 'expression'],
      'guard-for-in': 'warn',

      'import/export': 'warn',
      'import/extensions': ['warn', 'ignorePackages', {}],
      'import/first': 'warn',
      'import/newline-after-import': 'warn',
      'import/no-cycle': 'warn',
      'import/no-default-export': 'warn',
      'import/no-duplicates': 'warn',
      'import/no-extraneous-dependencies': ['warn', { devDependencies: true }],
      'import/no-mutable-exports': 'warn',
      'import/no-unresolved': ['error', { ignore: ['^eslint/config$'] }],
      'import/no-useless-path-segments': 'warn',
      'import/order': 'warn',
      'import/prefer-default-export': 'off',

      'jsx-a11y/alt-text': 'warn',
      'jsx-a11y/anchor-is-valid': 'warn',
      'jsx-a11y/aria-role': 'warn',
      'jsx-a11y/click-events-have-key-events': 'warn',
      'jsx-a11y/control-has-associated-label': 'warn',
      'jsx-a11y/iframe-has-title': 'warn',
      'jsx-a11y/no-noninteractive-tabindex': 'warn',
      'jsx-a11y/no-static-element-interactions': 'warn',

      'lines-between-class-members': ['warn', 'always', { exceptAfterSingleLine: true }],
      'max-classes-per-file': 'off',
      'no-await-in-loop': 'warn',
      'no-case-declarations': 'warn',
      'no-compare-neg-zero': 'warn',
      'no-console': ['warn', { allow: ['error', 'warn'] }],
      'no-constant-binary-expression': 'warn',
      'no-constant-condition': 'warn',
      'no-continue': 'warn',
      'no-dupe-else-if': 'warn',
      'no-dupe-keys': 'warn',
      'no-duplicate-case': 'warn',
      'no-else-return': ['warn', { allowElseIf: false }],
      'no-empty': ['warn', { allowEmptyCatch: true }],
      'no-empty-function': 'warn',
      'no-empty-pattern': 'warn',
      'no-extra-boolean-cast': 'warn',
      'no-fallthrough': 'warn',
      'no-irregular-whitespace': 'warn',
      'no-lone-blocks': 'warn',
      'no-lonely-if': 'warn',
      'no-multi-assign': 'warn',
      'no-nested-ternary': 'warn',
      'no-param-reassign': 'warn',
      'no-plusplus': 'off',
      'no-restricted-properties': 'warn',
      'no-restricted-syntax': 'warn',
      'no-return-await': 'warn',
      'no-return-assign': 'warn',
      'no-self-compare': 'warn',
      'no-sequences': 'warn',
      'no-shadow': 'off', // Handled by @typescript-eslint/no-shadow
      'no-template-curly-in-string': 'warn',
      'no-unexpected-multiline': 'warn',
      'no-undef': 'error',
      'no-undef-init': 'warn',
      'no-underscore-dangle': 'off',
      'no-unneeded-ternary': 'warn',
      'no-unsafe-optional-chaining': 'warn',
      'no-unreachable': 'warn',
      'no-unreachable-loop': 'warn',
      'no-unused-vars': 'off', // Handled by @typescript-eslint/no-unused-vars
      'no-use-before-define': 'off', // Handled by @typescript-eslint/no-use-before-define
      'no-useless-computed-key': 'warn',
      'no-useless-constructor': 'warn',
      'no-useless-escape': 'warn',
      'no-useless-rename': 'warn',
      'no-useless-return': 'warn',
      'no-void': 'warn',
      'object-shorthand': 'warn',
      'one-var': 'off',
      'operator-assignment': 'warn',
      'prefer-arrow-callback': 'warn',
      'prefer-const': 'warn',
      'prefer-destructuring': 'warn',
      'prefer-exponentiation-operator': 'off',
      'prefer-object-spread': 'warn',
      'prefer-regex-literals': 'warn',
      'prefer-template': 'warn',
      quotes: ['warn', 'single', { avoidEscape: true, allowTemplateLiterals: false }],
      radix: 'warn',

      'react/button-has-type': 'warn',
      'react/destructuring-assignment': 'warn',
      'react/display-name': 'off',
      'react/function-component-definition': [
        'warn',
        {
          namedComponents: 'arrow-function',
          unnamedComponents: 'arrow-function',
        },
      ],
      'react/jsx-boolean-value': 'warn',
      'react/jsx-curly-brace-presence': 'warn',
      'react/jsx-filename-extension': ['warn', { extensions: ['.jsx', '.tsx'] }],
      'react/jsx-fragments': 'warn',
      'react/jsx-key': ['warn', { checkFragmentShorthand: true }],
      'react/jsx-no-bind': 'warn',
      'react/jsx-no-constructed-context-values': 'warn',
      'react/jsx-no-useless-fragment': 'warn',
      'react/jsx-props-no-spreading': 'off',
      'react/no-array-index-key': 'warn',
      'react/no-children-prop': 'warn',
      'react/no-deprecated': 'warn',
      'react/no-unescaped-entities': 'warn',
      'react/no-unknown-property': 'warn',
      'react/no-unstable-nested-components': 'warn',
      'react/no-unused-prop-types': 'warn',
      'react/prop-types': 'off',
      'react/require-default-props': 'off',
      'react/self-closing-comp': 'warn',

      'react-hooks/exhaustive-deps': 'off',

      'react-refresh/only-export-components': 'warn',

      'spaced-comment': 'warn',
      yoda: 'warn',
    },
  },
]);
