import type { Metadata } from 'next';
import { Geist, Geist_Mono as geistMono } from 'next/font/google';
import type { ReactNode } from 'react';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMonoFont = geistMono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => (
  <html lang="en" className={`${geistSans.variable} ${geistMonoFont.variable}`}>
    <body>{children}</body>
  </html>
);

// eslint-disable-next-line import/no-default-export
export default RootLayout;
